
name: Release Kibana Notebooks Artifacts

on:
  push:
    tags:
      - 'v*'

env:
  PLUGIN_NAME: opendistroNotebooksKibana
  OD_VERSION: 1.12.0.0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Plugin
        uses: actions/checkout@v1

      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/kibana-oss
          ref: 7.10.0
          token: ${{secrets.OD_ACCESS}}
          path: kibana-notebooks/kibana

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.22.1'

      - name: Move Kibana Notebooks to Plugins Dir
        run: mv kibana-notebooks kibana/plugins/kibana-notebooks

      - name: Kibana Pluign Bootstrap
        run: |
          cd kibana/plugins/kibana-notebooks
          yarn kbn bootstrap

      - name: Build Artifact
        run: |
          cd kibana/plugins/kibana-notebooks
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip

      - name: Upload to S3
        run: |
          cd kibana/plugins/kibana-notebooks
          artifact=`ls ./build/*.zip`

          # inject build number before the suffix
          zip_outfile=`basename ${artifact%.zip}-build-${GITHUB_RUN_NUMBER}.zip`

          s3_prefix="s3://staging.artifacts.opendistroforelasticsearch.amazon.com/snapshots/kibana-plugins/notebooks/"

          echo "Copying ${artifact} to ${s3_prefix}${zip_outfile}"
          aws s3 cp --quiet $artifact ${s3_prefix}${zip_outfile}
