name: Test and Build OpenSearch Observability Backend Plugin

on: [pull_request, push]

env:
  OPENSEARCH_VERSION: '1.2.1-SNAPSHOT'
  OPENSEARCH_BRANCH: '1.2.1'
  COMMON_UTILS_BRANCH: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      - name: Build with Gradle
        run: |
          cd opensearch-observability
          ./gradlew build -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: opensearch-observability
          directory: opensearch-observability/
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Artifact Path
        run: |
          mkdir -p opensearch-observability-builds
          cp -r ./opensearch-observability/build/distributions/*.zip opensearch-observability-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: opensearch-observability
          path: opensearch-observability-builds
