
name: Release Trace Analytics Artifacts

on:
  push:
    tags:
      - 'v*'

env:
  PLUGIN_NAME: traceanalyticsDashboards
  OPENSEARCH_VERSION: 1.0.0-beta1
  OPENSEARCH_PLUGIN_VERSION: 1.0.0.0-beta1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout OpenSearch Dashboards
        uses: actions/checkout@v1
        with:
          repository: opensearch-project/Opensearch-Dashboards
          ref: ${{ env.OPENSEARCH_VERSION }}
          path: OpenSearch-Dashboards

      - name: Checkout Plugin
        uses: actions/checkout@v1
        with:
          path: OpenSearch-Dashboards/plugins/trace-analytics

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.23.1'

      - name: Plugin Bootstrap
        run: |
          yarn osd bootstrap

      - name: Build Artifact
        run: |
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OPENSEARCH_PLUGIN_VERSION }}.zip
          artifact=`ls ./build/*.zip`

          # TODO change to new bucket
          aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/kibana-plugins/opendistro-trace-analytics/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/downloads/*"
