
name: Release Trace Analytics Artifacts

on:
  push:
    tags:
      - 'v*'

env:
  PLUGIN_NAME: opendistroTraceAnalyticsKibana
  OD_VERSION: 1.13.0.0-alpha

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/kibana-oss
          ref: 7.10.2
          token: ${{secrets.OD_ACCESS}}
          path: kibana

      - name: Checkout Plugin
        uses: actions/checkout@v1
        with:
          path: kibana/plugins/trace-analytics

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.23.1'

      - name: Kibana Pluign Bootstrap
        run: |
          yarn kbn bootstrap

      - name: Build Artifact
        run: |
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip

      - name: Upload to S3
        run: |
          artifact=`ls ./build/*.zip`

          # inject build number before the suffix
          zip_outfile=`basename ${artifact%.zip}-build-${GITHUB_RUN_NUMBER}.zip`

          s3_prefix="s3://staging.artifacts.opendistroforelasticsearch.amazon.com/snapshots/kibana-plugins/trace-analytics/"

          echo "Copying ${artifact} to ${s3_prefix}${zip_outfile}"
          aws s3 cp --quiet $artifact ${s3_prefix}${zip_outfile}
