
name: Release Kibana Notebooks Artifacts

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/kibana-oss
          ref: 7.9.1
          token: ${{secrets.OD_ACCESS}}
          path: kibana

      - name: Checkout Plugin
        uses: actions/checkout@v1
        with:
          path: kibana/plugins/kibana-notebooks

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.22.0'

      - name: Kibana Pluign Bootstrap
        run: |
          yarn kbn bootstrap

      - name: Build Artifact
        run: |
          yarn build
          artifact=`ls ./build/*.zip`

          aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/kibana-plugins/opendistro-notebooks/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/downloads/*"
