
name: Test and Build Trace Analytics

on: [pull_request, push]

env:
  PLUGIN_NAME: traceAnalyticsDashboards
  OPENSEARCH_VERSION: '1.0'
  OPENSEARCH_PLUGIN_VERSION: 1.0.0.0-rc1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenSearch Dashboards
        uses: actions/checkout@v1
        with:
          repository: opensearch-project/Opensearch-Dashboards
          ref: ${{ env.OPENSEARCH_VERSION }}
          path: OpenSearch-Dashboards
      - name: Checkout Plugin
        uses: actions/checkout@v1
        with:
          path: OpenSearch-Dashboards/plugins/trace-analytics
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.23.1'
      - name: Plugin Bootstrap
        run: |
          yarn osd bootstrap
      - name: Test
        run: |
          yarn test --coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: dashboards-notebooks
          directory: OpenSearch-Dashboards/plugins/
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build Artifact
        run: |
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OPENSEARCH_PLUGIN_VERSION }}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: trace-analytics
          path: ./build
